version: '3.8'
services:
  # backend:
  #   build:
  #     context: ./
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - PORT=3000
  #     - DATABASE_URL=postgresql://postgres:cookbook_password@db:5432/cookbook_db
  #   depends_on:
  #     - db
  #   networks:
  #     - mynetwork
  #   volumes:
  #     - .:/app
  #     - /app/node_modules  
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cookbook_password
      - POSTGRES_DB=cookbook_db
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Cg400288
    depends_on:
      - db
    ports:
      - "5050:80"    
    networks:
      - mynetwork  

networks:
  mynetwork:
    driver: bridge
